import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
      </Head>

      <main className={styles.main}>
        <div className="badge-base LI-profile-badge" data-locale="es_ES" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="jua-diaz-dev" data-version="v1"><a className="badge-base__link LI-simple-link" href="https://co.linkedin.com/in/jua-diaz-dev?trk=profile-badge">Juan Díaz</a></div>
      </main>
    </div>
  )
}

export default Home
